# Generated by Django 5.2.4 on 2025-08-03 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('categoria_peso', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('equipe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Desempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_competicao', models.DateField()),
                ('vitorias', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('ippons', models.IntegerField(default=0)),
                ('wazaris', models.IntegerField(default=0)),
                ('penalidades', models.IntegerField(default=0)),
                ('equipe', models.CharField(max_length=100)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desempenhos', to='datatame_app.atleta')),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_treino', models.DateField()),
                ('tipo_treino', models.CharField(max_length=100)),
                ('duracao_minutos', models.IntegerField()),
                ('intensidade', models.IntegerField()),
                ('equipe', models.CharField(max_length=100)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='datatame_app.atleta')),
            ],
        ),
    ]
