# Generated by Django 5.2.4 on 2025-11-26 22:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atleta', models.CharField(max_length=200)),
                ('dependencia_chave', models.CharField(max_length=200)),
                ('ponto_menos_decisivo', models.CharField(max_length=200)),
                ('estilo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('categoria_peso', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade_atletas', models.IntegerField()),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Desempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_competicao', models.DateField()),
                ('vitorias', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('ippons', models.IntegerField(default=0)),
                ('wazaris', models.IntegerField(default=0)),
                ('penalidades', models.IntegerField(default=0)),
                ('equipe', models.CharField(max_length=100)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desempenhos', to='datatame_app.atleta')),
            ],
        ),
        migrations.AddField(
            model_name='atleta',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datatame_app.equipe'),
        ),
        migrations.CreateModel(
            name='Luta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adversario', models.CharField(max_length=100)),
                ('golpes_atleta', models.IntegerField()),
                ('golpes_adversario', models.IntegerField()),
                ('vantagem_atleta', models.IntegerField(default=0)),
                ('vantagem_adversario', models.IntegerField(default=0)),
                ('penalidade_atleta', models.IntegerField(default=0)),
                ('penalidade_adversario', models.IntegerField(default=0)),
                ('resultado', models.CharField(max_length=20)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('diferenca_golpes', models.IntegerField(default=0)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datatame_app.atleta')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datatame_app.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='LutaRegistrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adversario', models.CharField(blank=True, max_length=255, null=True)),
                ('tempo_luta_segundos', models.IntegerField(blank=True, null=True)),
                ('shidos_atleta', models.IntegerField(default=0)),
                ('shidos_oponente', models.IntegerField(default=0)),
                ('numero_pausas', models.IntegerField(default=0)),
                ('ippon_atl', models.IntegerField(default=0)),
                ('ippon_op', models.IntegerField(default=0)),
                ('wazari_atl', models.IntegerField(default=0)),
                ('wazari_op', models.IntegerField(default=0)),
                ('yuko_atl', models.IntegerField(default=0)),
                ('yuko_op', models.IntegerField(default=0)),
                ('newaza_tentativas_atl', models.IntegerField(default=0)),
                ('newaza_tentativas_op', models.IntegerField(default=0)),
                ('newaza_acertos_atl', models.IntegerField(default=0)),
                ('newaza_acertos_op', models.IntegerField(default=0)),
                ('tewaza_tentativas_atl', models.IntegerField(default=0)),
                ('tewaza_tentativas_op', models.IntegerField(default=0)),
                ('tewaza_acertos_atl', models.IntegerField(default=0)),
                ('tewaza_acertos_op', models.IntegerField(default=0)),
                ('koshiwaza_tentativas_atl', models.IntegerField(default=0)),
                ('koshiwaza_tentativas_op', models.IntegerField(default=0)),
                ('koshiwaza_acertos_atl', models.IntegerField(default=0)),
                ('koshiwaza_acertos_op', models.IntegerField(default=0)),
                ('ashiwaza_tentativas_atl', models.IntegerField(default=0)),
                ('ashiwaza_tentativas_op', models.IntegerField(default=0)),
                ('ashiwaza_acertos_atl', models.IntegerField(default=0)),
                ('ashiwaza_acertos_op', models.IntegerField(default=0)),
                ('sutemiwaza_tentativas_atl', models.IntegerField(default=0)),
                ('sutemiwaza_tentativas_op', models.IntegerField(default=0)),
                ('sutemiwaza_acertos_atl', models.IntegerField(default=0)),
                ('sutemiwaza_acertos_op', models.IntegerField(default=0)),
                ('iniciativa_pegada_atl', models.IntegerField(default=0)),
                ('iniciativa_pegada_op', models.IntegerField(default=0)),
                ('resultado', models.IntegerField(choices=[(1, 'Vitória'), (0, 'Derrota')], default=0)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lutas', to='datatame_app.atleta')),
            ],
            options={
                'verbose_name': 'Luta registrada',
                'verbose_name_plural': 'Lutas registradas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_treino', models.DateField()),
                ('tipo_treino', models.CharField(max_length=100)),
                ('duracao_minutos', models.IntegerField()),
                ('intensidade', models.IntegerField()),
                ('equipe', models.CharField(max_length=100)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='datatame_app.atleta')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ATLETA', 'Atleta'), ('EQUIPE', 'Equipe')], max_length=10)),
                ('atleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datatame_app.atleta')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datatame_app.equipe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datatame_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datatame_app.user'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datatame_app.user'),
        ),
    ]
